### ISSUE TITLE
Make dungeons frequency configurable via config file

### ISSUE THREAD

**Issue by florian-berger** [BarionLP/DungeonsEnhanced#35]
**Please describe your idea (If it is related to a problem create a bug report and note your idea as a solution). **
Hi,

I wish it is possible to change the frequency of the dungeons that are generated. In my modpack, the structures should be rare. But they are generated way too often. The description on CurseForge says something about a "spacing" value, but the config file doesn't contain a spacing setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by BarionLP** [comment]
this is only possible via a datapack, I'll create a guide and link it here

back in 1.19 mojang rewrote structures using a data driven approach which made the config approach unusable.
Modding Legacy invented a workaround for the biomes as their biome filtering system is quite useful. 
For dungeon frequency this would be irresponsible because we are essentially working against mojang.
In the future I might figure out a non destructive way to allow for config modification.
